### ISSUE TITLE
Prevent database from being overwritten on docker-compose up

### ISSUE THREAD

**Issue by ibdf** [CityOfPhiladelphia/phila.gov-docker-dev#1]
If you do `docker-compose up` it will try to pull a new database and overwrite the current one, unless there's a database file in the db-data folder already. This is a bit dangerous. Maybe we can pass the database as an option.

**Comment by alejandroxlopez** [comment]
The issue was addressed and fixed in the Master branch.
Commit: a49c82a270ce723f51526ff60fe3ad2de20aecc8
